# Generated by Django 3.2.5 on 2021-07-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picshare', '0003_auto_20210721_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='post_tags', to='picshare.Tag'),
        ),
    ]
