# Generated by Django 3.2.5 on 2021-07-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picshare', '0004_auto_20210722_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='post_tags', to='picshare.Tag'),
        ),
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='image_tags', to='picshare.Tag'),
        ),
    ]
